TEX=latex
FILE=sml-defn

all: revision.tex
	$(TEX) $(FILE)
	bibtex $(FILE)
	$(TEX) $(FILE)
	$(TEX) $(FILE)
	dvipdfmx $(FILE).dvi

.PHONY: revision.tex

# https://tex.stackexchange.com/a/78089/14751
revision.tex:
	echo "% Autogenerated, do not edit" > revision.tex
	echo "\\\\newcommand{\\\\revisiondate}{`git log -1 --format=\"%aI\"`}" >> revision.tex
	echo "\\\\newcommand{\\\\revision}{`git log -1 --format=\"%h\"`}" >> revision.tex